# Generated by Django 2.1 on 2018-08-05 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImmFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Immediate Family',
                'verbose_name_plural': 'Immediate Families',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(blank=True, default=None, max_length=200, unique=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('participation', models.BooleanField(default=0)),
                ('imm_family', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='family.ImmFamily')),
                ('match', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_of', to='family.Member')),
            ],
            options={
                'ordering': ['birthday', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(blank=True, default=None, max_length=200, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='member',
            name='pool',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='family.Pool'),
        ),
        migrations.AddField(
            model_name='member',
            name='prev_match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_match_of', to='family.Member'),
        ),
        migrations.AddField(
            model_name='member',
            name='spouse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='family.Member'),
        ),
    ]
